version: '3'

services:

  ssl:
    image: paulczar/omgwtfssl
    container_name: dash_ssl
    restart: "no"
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=${SSL_SUBJECT}
      - CA_SUBJECT=${CA_SUBJECT}
      - SSL_KEY=${SSL_KEY}
      - SSL_CSR=${SSL_CSR}
      - SSL_CERT=${SSL_CERT}

  proxy:
    image: nginx
    container_name: dash_proxy
    restart: unless-stopped
    ports:
      - 8080:443/tcp
    volumes:
      - certs:/etc/ssl
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy-tier
    depends_on:
      - ssl

  pgsql:
    image: postgres
    container_name: dash_pgsql
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  dash:
    build:
      context: ./dash
    container_name: dash_dash
    restart: unless-stopped
    command: python app.py
    volumes:
      - ~/git/cordash/:/code
    depends_on:
      - pgsql

volumes:
  certs:
  pgdata:

networks:
  proxy-tier:
